import { PHI_SHARED_PACKAGE_NAME } from "./package";
import { createPhiModuleIdentifier, createPhiRuntimeModuleId, isPhiModuleScopedIdentifier } from "./module-identity";

/**
 * Which module owns which first-party identifier. The runtime module catalog is the source: it refuses
 * two modules claiming one key, so this table restates a fact rather than deciding one. Keys are
 * `<namespace>/<key as the factory receives it>`; the value is the owning module and the leaf name
 * after the owner's own prefix is dropped, because a module never needs to repeat its name inside its
 * own namespace.
 */
const PHI_RUNTIME_MODULE_OWNERSHIP: Readonly<Record<string, readonly [module: string, leaf: string]>> = {
  "background-patterns/checker": ["core", "checker"],
  "background-patterns/crosshatch": ["core", "crosshatch"],
  "background-patterns/dots": ["core", "dots"],
  "background-patterns/grid": ["core", "grid"],
  "background-patterns/stripes": ["core", "stripes"],
  "calendars/gregory": ["core", "gregory"],
  "collections/media": ["asset", "media"],
  "controller/accounting-base": ["accounting", "base"],
  "controller/admin": ["admin", "default"],
  "controller/app-base": ["app", "base"],
  "controller/asset": ["asset", "default"],
  "controller/auth": ["auth", "default"],
  "controller/builder": ["builder", "default"],
  "controller/core": ["core", "default"],
  "controller/dashboard": ["dashboard", "default"],
  "controller/editor": ["editor", "default"],
  "controller/form": ["core", "form"],
  "controller/form-builder": ["form-builder", "default"],
  "controller/groups": ["groups", "default"],
  "controller/localization": ["localization", "default"],
  "controller/observability": ["observability", "default"],
  "controller/public-base": ["public", "base"],
  "controller/revisions": ["revisions", "default"],
  "controller/theme": ["theme", "default"],
  "controller/user-management": ["user-management", "default"],
  "form-field/asset-focal-rect": ["asset", "focal-rect"],
  "form-field/auth-terms-consent": ["auth", "terms-consent"],
  "form-field/cascader": ["core", "cascader"],
  "form-field/checkbox": ["core", "checkbox"],
  "form-field/checkbox-group": ["core", "checkbox-group"],
  "form-field/datetime": ["core", "datetime"],
  "form-field/email": ["core", "email"],
  "form-field/hidden": ["core", "hidden"],
  "form-field/honeypot": ["core", "honeypot"],
  "form-field/multi-select": ["core", "multi-select"],
  "form-field/number": ["core", "number"],
  "form-field/password": ["core", "password"],
  "form-field/segmented": ["core", "segmented"],
  "form-field/select": ["core", "select"],
  "form-field/slider": ["core", "slider"],
  "form-field/switch": ["core", "switch"],
  "form-field/table": ["core", "table"],
  "form-field/tel": ["core", "tel"],
  "form-field/text": ["core", "text"],
  "form-field/textarea": ["core", "textarea"],
  "form-field/tree": ["core", "tree"],
  "form-field/url": ["core", "url"],
  "form-handler/admin-settings-general": ["admin", "settings-general"],
  "form-handler/asset-folder-create": ["asset", "folder-create"],
  "form-handler/asset-media-settings": ["asset", "media-settings"],
  "form-handler/asset-metadata": ["asset", "metadata"],
  "form-handler/auth-admin-installation-create": ["auth", "admin-installation-create"],
  "form-handler/auth-admin-installation-update": ["auth", "admin-installation-update"],
  "form-handler/auth-admin-password-method": ["auth", "admin-password-method"],
  "form-handler/auth-admin-policy": ["auth", "admin-policy"],
  "form-handler/auth-admin-totp-policy": ["auth", "admin-totp-policy"],
  "form-handler/auth-confirm": ["auth", "confirm"],
  "form-handler/auth-confirm-preview": ["auth", "confirm-preview"],
  "form-handler/auth-login": ["auth", "login"],
  "form-handler/auth-provider-link-confirm": ["auth", "provider-link-confirm"],
  "form-handler/auth-registration": ["auth", "registration"],
  "form-handler/auth-registration-confirm": ["auth", "registration-confirm"],
  "form-handler/auth-reset-password": ["auth", "reset-password"],
  "form-handler/auth-reset-password-confirm": ["auth", "reset-password-confirm"],
  "form-handler/contact": ["public", "contact"],
  "form-handler/groups-create": ["groups", "create"],
  "form-handler/groups-membership": ["groups", "membership"],
  "form-handler/groups-my-membership": ["groups", "my-membership"],
  "form-handler/localization-editor-translation": ["localization", "editor-translation"],
  "form-handler/localization-site-locales": ["localization", "site-locales"],
  "form-handler/user-management-create": ["user-management", "create"],
  "form-handler/user-management-edit": ["user-management", "edit"],
  "form-validation/email": ["core", "email"],
  "form-validation/exact-length": ["core", "exact-length"],
  "form-validation/matches-field": ["core", "matches-field"],
  "form-validation/max-length": ["core", "max-length"],
  "form-validation/min-length": ["core", "min-length"],
  "form-validation/min-letters": ["core", "min-letters"],
  "form-validation/number": ["core", "number"],
  "form-validation/pattern": ["core", "pattern"],
  "form-validation/required": ["core", "required"],
  "form-validation/tel": ["core", "tel"],
  "form-validation/url": ["core", "url"],
  "forms/admin/settings-general": ["admin", "settings-general"],
  "forms/asset/folder-create": ["asset", "folder-create"],
  "forms/asset/media-settings": ["asset", "media-settings"],
  "forms/asset/metadata": ["asset", "metadata"],
  "forms/auth/admin-installation-create": ["auth", "admin-installation-create"],
  "forms/auth/admin-installation-edit": ["auth", "admin-installation-edit"],
  "forms/auth/admin-password-method": ["auth", "admin-password-method"],
  "forms/auth/admin-policy": ["auth", "admin-policy"],
  "forms/auth/admin-totp-policy": ["auth", "admin-totp-policy"],
  "forms/builder/effects/appearance": ["builder", "effects/appearance"],
  "forms/builder/effects/transitions": ["builder", "effects/transitions"],
  "forms/builder/effects/viewport": ["builder", "effects/viewport"],
  "forms/builder/page-meta": ["builder", "page-meta"],
  "forms/builder/signal-wiring": ["builder", "signal-wiring"],
  "forms/confirm": ["auth", "confirm"],
  "forms/contact": ["public", "contact"],
  "forms/groups/create": ["groups", "create"],
  "forms/groups/membership": ["groups", "membership"],
  "forms/groups/my-membership": ["groups", "my-membership"],
  "forms/localization/editor-translation": ["localization", "editor-translation"],
  "forms/localization/site-locales": ["localization", "site-locales"],
  "forms/login": ["auth", "login"],
  "forms/provider-link-confirmation": ["auth", "provider-link-confirmation"],
  "forms/registration": ["auth", "registration"],
  "forms/reset-password": ["auth", "reset-password"],
  "forms/user-management/create": ["user-management", "create"],
  "forms/user-management/edit": ["user-management", "edit"],
  "options/admin-site-locales": ["localization", "admin-site-locales"],
  "options/builder-navigation-sets": ["builder", "navigation-sets"],
  "options/builder-pages": ["builder", "pages"],
  "options/builder-signal-receiver-capabilities": ["builder", "signal-receiver-capabilities"],
  "options/builder-signal-receivers": ["builder", "signal-receivers"],
  "options/builder-signal-sender-capabilities": ["builder", "signal-sender-capabilities"],
  "options/builder-signal-senders": ["builder", "signal-senders"],
  "options/forms": ["builder", "forms"],
  "options/group-member-candidates": ["groups", "group-member-candidates"],
  "options/groups": ["groups", "groups"],
  "options/localization-locales": ["localization", "locales"],
  "options/media-folders": ["asset", "media-folders"],
  "options/my-groups": ["groups", "my-groups"],
  "options/revision-bindings": ["revisions", "revision-bindings"],
  "options/runtime-modules": ["builder", "runtime-modules"],
  "options/site-locales": ["localization", "site-locales"],
  "options/spacing-scale": ["core", "spacing-scale"],
  "options/theme-keys": ["theme", "keys"],
  "options/theme-presets": ["theme", "presets"],
  "options/translation-contexts": ["localization", "translation-contexts"],
  "tables/auth-installations": ["auth", "installations"],
  "signals/background-config": ["core", "background-config"],
  "signals/border-config": ["core", "border-config"],
  "signals/brand-theme": ["theme", "brand"],
  "signals/builder-chrome": ["builder", "chrome"],
  "signals/builder-inspector": ["builder", "inspector"],
  "signals/builder-layout": ["builder", "layout"],
  "signals/builder-navigation": ["builder", "navigation"],
  "signals/builder-node-selection": ["builder", "node-selection"],
  "signals/collection-action": ["core", "collection-action"],
  "signals/drag-drop": ["core", "drag-drop"],
  "signals/form-error": ["core", "form-error"],
  "signals/form-field": ["core", "form-field"],
  "signals/form-result": ["core", "form-result"],
  "signals/form-state": ["core", "form-state"],
  "signals/form-submit": ["core", "form-submit"],
  "signals/form-touched": ["core", "form-touched"],
  "signals/form-validity": ["core", "form-validity"],
  "signals/form-values": ["core", "form-values"],
  "signals/localization-workspace": ["localization", "workspace"],
  "signals/markdown-toc": ["core", "markdown-toc"],
  "signals/media-asset-selection": ["asset", "selection"],
  "signals/message": ["core", "message"],
  "signals/notification": ["core", "notification"],
  "signals/overlay-close-request": ["core", "overlay-close-request"],
  "signals/page-meta": ["core", "page-meta"],
  "signals/pagination": ["core", "pagination"],
  "signals/revisions-draft-status": ["revisions", "draft-status"],
  "signals/runtime-condition-state": ["core", "runtime-condition-state"],
  "signals/runtime-theme": ["core", "runtime-theme"],
  "signals/stack-meta": ["core", "stack-meta"],
  "signals/table-action": ["core", "table-action"],
  "signals/table-binding-params": ["core", "table-binding-params"],
  "signals/table-column-order": ["core", "table-column-order"],
  "signals/table-expansion": ["core", "table-expansion"],
  "signals/table-filters": ["core", "table-filters"],
  "signals/table-mutation": ["core", "table-mutation"],
  "signals/table-query": ["core", "table-query"],
  "signals/table-selection": ["core", "table-selection"],
  "signals/table-state": ["core", "table-state"],
  "signals/temporal-selection": ["core", "temporal-selection"],
  "signals/tree-action": ["core", "tree-action"],
  "signals/tree-binding-params": ["core", "tree-binding-params"],
  "signals/tree-mutation": ["core", "tree-mutation"],
  "signals/tree-state": ["core", "tree-state"],
  "tables/builder-navigation": ["builder", "navigation"],
  "tables/builder-signal-routes": ["builder", "signal-routes"],
  "tables/content": ["core", "content"],
  "tables/groups": ["groups", "groups"],
  "tables/localization": ["localization", "localization"],
  "tables/observability": ["observability", "observability"],
  "tables/revisions": ["revisions", "revisions"],
  "tables/user-management": ["user-management", "user-management"],
  "trees/builder-page-source": ["builder", "page-source"],
};

/**
 * Composes `@phis/ui/modules/<module>/<namespace>/<leaf>` for a first-party identifier. A foreign
 * package composes its own key from its own name and never passes through here.
 */
export function createPhiModuleScopedKey<TNamespace extends string>(
  namespace: TNamespace,
  key: string,
): `${string}/${TNamespace}/${string}` {
  const owned = PHI_RUNTIME_MODULE_OWNERSHIP[`${namespace}/${key}`];
  if (!owned) {
    throw new Error(`Unowned first-party identifier "${namespace}/${key}".`);
  }
  const [moduleKey, leaf] = owned;
  return createPhiModuleIdentifier(
    createPhiRuntimeModuleId(PHI_SHARED_PACKAGE_NAME, moduleKey),
    namespace,
    leaf,
  ) as `${string}/${TNamespace}/${string}`;
}

/**
 * Whether a value names something in `namespace`, first-party or not. The owner in front of the
 * namespace is either a bare package or a package followed by `/modules/<module>`; a foreign package
 * uses either form, because the grammar describes where a name comes from and not who wrote it.
 *
 * This is the reader for what `createPhiModuleScopedKey` writes, and it lives beside it so widening
 * one without the other is not possible.
 */
export function isPhiModuleScopedKey(namespace: string, value: unknown): boolean {
  return isPhiModuleScopedIdentifier(namespace, value);
}
