import {
  definePhiRuntimeModuleServerAreaContribution,
  type PhiRuntimeModuleServerAreaContribution,
} from "./plugins/runtime-modules/area-contributions";

/**
 * What a Module package exports, and under which names.
 *
 * A Module outside `@phis/ui` reaches a Site through a file generated by `phis-cli`, and a generator
 * cannot guess an export it was never told about. `package.json#exports` says where an entrypoint is,
 * never what is inside it -- so the names are fixed here instead, the same way an Add-on artifact has
 * exactly one export called `phiServerAddon`.
 *
 * One fixed export per boundary, and the boundaries are the ones MODULES.md already requires:
 *
 *   ./server            phiModuleServerContributions
 *   ./client            phiModuleClientContribution
 *   ./authoring-client  phiModuleAuthoringContributions
 *
 * A Module never names an Area. Where its contribution belongs follows from `eligibleAreas` on its own
 * definition, which is also what decides whether a Site may select it for an Area -- one statement, read
 * in both places, rather than a second list that can disagree with the first.
 */

export type PhiModuleServerContributions = readonly PhiRuntimeModuleServerAreaContribution[];

export function definePhiModuleServerContributions(
  contributions: PhiModuleServerContributions,
): PhiModuleServerContributions {
  // Validating here rather than at Site assembly means a Module author sees the mismatch while building
  // their own package, not the operator who installed it.
  return contributions.map((contribution) =>
    definePhiRuntimeModuleServerAreaContribution(contribution),
  );
}

export type { PhiRuntimeModuleServerAreaContribution };
