export {
  PHI_APP_RUNTIME_MODULE_CALENDAR_ADAPTER_CLIENT_MANIFEST,
  PHI_APP_RUNTIME_MODULE_CONTROLLER_CLIENT_MANIFEST,
  PHI_APP_RUNTIME_MODULE_DATA_PROVIDER_CLIENT_MANIFEST,
  PHI_APP_RUNTIME_MODULE_RENDER_CLIENT_MANIFEST,
} from "./plugins/runtime-modules/client-manifests/app";
