import type { PhiRuntimeModuleDataProviderDescriptor } from "../contracts";
import { PHI_LOCALIZATION_RUNTIME_DATA_PROVIDER_KEYS } from "./ids";
import { PHI_LOCALIZATION_RUNTIME_MODULE_ID } from "./ids";

export const PHI_LOCALIZATION_RUNTIME_DATA_PROVIDER_DESCRIPTORS = [
  {
    key: PHI_LOCALIZATION_RUNTIME_DATA_PROVIDER_KEYS.platformLocales,
    ownerModuleId: PHI_LOCALIZATION_RUNTIME_MODULE_ID,
    kind: "options",
    executionMode: "live",
    authoringMode: "none",
    title: "Localization locales",
    description: "Locales available to site localization Forms and Controls.",
  },
  {
    key: PHI_LOCALIZATION_RUNTIME_DATA_PROVIDER_KEYS.adminSiteLocales,
    ownerModuleId: PHI_LOCALIZATION_RUNTIME_MODULE_ID,
    kind: "options",
    executionMode: "live",
    authoringMode: "none",
    title: "Admin site locales",
    description: "Locales enabled for the current site in Admin localization controls.",
  },
  {
    key: PHI_LOCALIZATION_RUNTIME_DATA_PROVIDER_KEYS.siteLocales,
    ownerModuleId: PHI_LOCALIZATION_RUNTIME_MODULE_ID,
    kind: "options",
    executionMode: "live",
    authoringMode: "none",
    title: "Site locales",
    description: "Locales enabled for the current site.",
  },
  {
    key: PHI_LOCALIZATION_RUNTIME_DATA_PROVIDER_KEYS.translationContexts,
    ownerModuleId: PHI_LOCALIZATION_RUNTIME_MODULE_ID,
    kind: "options",
    executionMode: "live",
    authoringMode: "none",
    title: "Translation contexts",
    description: "Message contexts available in the current site translation workspace.",
  },
  {
    key: PHI_LOCALIZATION_RUNTIME_DATA_PROVIDER_KEYS.table,
    ownerModuleId: PHI_LOCALIZATION_RUNTIME_MODULE_ID,
    kind: "table",
    executionMode: "live",
    authoringMode: "none",
    title: "Localization tables",
    description: "Locale and translation data exposed by the Localization module.",
    resources: [
      {
        resourceKey: "siteLocaleSettings",
        title: "Site locale settings",
        rowIdentityPath: "id",
        fields: [
          { key: "id", title: "ID", type: "string", required: true },
          { key: "sourceLocale", title: "Source locale", type: "string" },
          {
            key: "defaultLocale",
            title: "Default locale",
            type: "enum",
            required: true,
            mutable: true,
            optionsProvider: { providerKey: PHI_LOCALIZATION_RUNTIME_DATA_PROVIDER_KEYS.platformLocales },
          },
          {
            key: "availableLocales",
            title: "Available locales",
            type: "enum[]",
            required: true,
            mutable: true,
            optionsProvider: { providerKey: PHI_LOCALIZATION_RUNTIME_DATA_PROVIDER_KEYS.platformLocales },
          },
        ],
        query: {
          search: false,
          filterFields: [],
          sorting: "none",
          pagination: "none",
        },
        recordRead: true,
        actions: [],
      },
      {
        resourceKey: "siteTranslations",
        title: "Site translations",
        rowIdentityPath: "id",
        summaryFields: [
          { key: "localeTotal", title: "Locale translations", type: "number" },
        ],
        fields: [
          { key: "id", title: "ID", type: "string", required: true },
          { key: "msgId", title: "Message ID", type: "number", required: true },
          {
            key: "locale",
            title: "Locale",
            type: "enum",
            required: true,
            optionsProvider: { providerKey: PHI_LOCALIZATION_RUNTIME_DATA_PROVIDER_KEYS.adminSiteLocales },
          },
          { key: "source", title: "Source", type: "string" },
          { key: "sourceContext", title: "Context", type: "string" },
          { key: "translation", title: "Translation", type: "string", required: true, mutable: true },
          { key: "protected", title: "Protected external source", type: "boolean" },
          { key: "updatedAt", title: "Updated", type: "datetime" },
        ],
        query: {
          search: true,
          filterFields: ["locale"],
          sorting: "none",
          pagination: "offset",
          facets: ["site", "platformLocales", "selectedLocale"],
        },
        actions: [
          {
            key: "delete", title: "Delete translation", scope: "row",
            disabledWhen: { source: "row", valuePath: "protected", operator: "truthy" },
            intent: "destructive",
            confirmation: "required",
          },
          {
            key: "deleteSelected", title: "Delete selected translations", scope: "selection",
            intent: "destructive",
            confirmation: "required",
          },
          { key: "saveLocales", title: "Save locales", scope: "resource", valueType: "json" },
        ],
      },
      {
        resourceKey: "editorTranslations",
        title: "Editor translations",
        rowIdentityPath: "id",
        fields: [
          { key: "id", title: "ID", type: "string", required: true },
          { key: "msgId", title: "Message ID", type: "number", required: true },
          { key: "locale", title: "Locale", type: "string", required: true },
          { key: "source", title: "Source", type: "string" },
          { key: "sourceContext", title: "Context", type: "string" },
          { key: "translation", title: "Translation", type: "string", mutable: true },
          { key: "hasTranslation", title: "Has translation", type: "boolean" },
          { key: "protected", title: "Protected external source", type: "boolean" },
          { key: "status", title: "Status", type: "string" },
          { key: "createdAt", title: "Created", type: "datetime" },
          { key: "updatedAt", title: "Updated", type: "datetime" },
        ],
        query: {
          search: true,
          filterFields: ["locale", "context", "status"],
          sorting: "none",
          pagination: "offset",
          facets: ["sourceLocale", "selectedLocale", "availableLocales", "contexts"],
        },
        recordRead: true,
        actions: [
          { key: "saveTranslation", title: "Save translation", scope: "row", valueType: "json" },
          {
            key: "delete", title: "Delete translation", scope: "row",
            disabledWhen: { match: "any", conditions: [
              { source: "row", valuePath: "hasTranslation", operator: "falsy" },
              { source: "row", valuePath: "protected", operator: "truthy" },
            ] },
            intent: "destructive",
            confirmation: "required",
          },
          { key: "refresh", title: "Refresh", scope: "resource" },
        ],
      },
    ],
  },
] satisfies readonly PhiRuntimeModuleDataProviderDescriptor[];
