import "server-only";

import { PHI_TR_CTX_WEB_UI_LABEL, type PhiGlobalTranslatorOptions } from "../../../gateway/tr";
import { definePhiLabelSet, getPhiLabelSet } from "../../../gateway/label-set";

const PHI_ADMIN_USERS_TABLE_WIDGET_LABEL_SET = definePhiLabelSet({
  key: "widget:admin-users-table",
  ctx: PHI_TR_CTX_WEB_UI_LABEL,
  labels: {
    title: "Users",
    description: "Manage local site users, roles, and password resets in one list.",
    search_placeholder: "Search users",
    reset_label: "Reset",
    add_label: "Add user",
    footer_count: "%1 users of %2 total",
    account_type_all: "All",
    account_type_shop: "Shop",
    account_type_roles: "Local roles",
    account_type_auth: "Auth",
    enabled_all: "All",
    enabled_enabled: "Enabled",
    enabled_disabled: "Disabled",
    enabled_self_disabled: "Your own account cannot be enabled or disabled here.",
    column_enabled: "Enabled",
    column_account: "Account",
    column_name: "Name",
    column_email: "Email",
    column_roles: "Roles",
    column_user_flags: "User flags",
    column_site_flags: "Site flags",
    column_last_login: "Last login",
    column_created: "Created",
    column_actions: "Actions",
    column_login: "Login",
    column_status: "Status",
    column_last_seen: "Last seen",
    column_expires: "Expires",
    column_ip: "IP",
    column_user_agent: "User agent",
    empty_title: "No users found.",
    empty_text: "Try widening the filters.",
    editor_add_title: "Add user",
    editor_edit_title: "Edit user",
    editor_edit_title_with_name: "Edit user %1",
    editor_create_button: "Create",
    editor_save_button: "Save",
    editor_first_name: "First name",
    editor_last_name: "Last name",
    editor_email: "Email",
    editor_company: "Company",
    editor_roles: "Roles",
    editor_roles_placeholder: "Choose roles",
    editor_change_password: "Require password reset",
    editor_create_password_hint: "New users are created with a temporary password and receive a reset link.",
    editor_auth_only_hint: "Leave roles empty for an auth-only account.",
    editor_self_role_hint: "Leave roles empty for an auth-only account. Your own role can be changed only for other users.",
    history_title: "Login history",
    history_title_with_name: "Login history for %1",
    history_loading: "Loading login history...",
    history_empty: "No logins found.",
    history_error_title: "Login history failed",
    delete_confirm_title: "Delete user?",
    delete_confirm_self: "You cannot delete your own account here.",
    delete_confirm_medusa: "Medusa-managed accounts cannot be deleted here.",
    delete_confirm_shared: "This removes the user from the current site. Other site memberships stay intact.",
    delete_confirm_irreversible: "Without a backup, this action cannot be undone.",
    delete_ok_label: "Delete",
    delete_cancel_label: "Cancel",
    action_edit_label: "Edit user",
    action_edit_disabled_label: "Medusa-managed accounts cannot be edited here.",
    action_history_label: "Show login history",
    action_delete_label: "Delete user",
    feedback_load_users: "Failed to load users.",
    feedback_load_history: "Failed to load login history.",
    feedback_update_user: "Failed to update user.",
    feedback_delete_user: "Failed to delete user.",
    feedback_save_user: "Failed to save user.",
    feedback_create_user: "Failed to create user.",
    feedback_update_user_generic: "Failed to update user.",
    feedback_delete_user_generic: "Failed to delete user.",
  },
});

export async function getPhiAdminUsersTableWidgetLabels(options: PhiGlobalTranslatorOptions) {
  const labels = await getPhiLabelSet(options, PHI_ADMIN_USERS_TABLE_WIDGET_LABEL_SET);
  return {
    title: labels.title,
    description: labels.description,
    searchPlaceholder: labels.search_placeholder,
    resetLabel: labels.reset_label,
    addLabel: labels.add_label,
    footer: labels.footer_count,
    accountTypes: {
      all: labels.account_type_all,
      shop: labels.account_type_shop,
      roles: labels.account_type_roles,
      auth: labels.account_type_auth,
    },
    enabledOptions: {
      all: labels.enabled_all,
      enabled: labels.enabled_enabled,
      disabled: labels.enabled_disabled,
      selfDisabled: labels.enabled_self_disabled,
    },
    columns: {
      enabled: labels.column_enabled,
      account: labels.column_account,
      name: labels.column_name,
      email: labels.column_email,
      roles: labels.column_roles,
      userFlags: labels.column_user_flags,
      siteFlags: labels.column_site_flags,
      lastLogin: labels.column_last_login,
      created: labels.column_created,
      actions: labels.column_actions,
      login: labels.column_login,
      status: labels.column_status,
      lastSeen: labels.column_last_seen,
      expires: labels.column_expires,
      ip: labels.column_ip,
      userAgent: labels.column_user_agent,
    },
    empty: {
      title: labels.empty_title,
      text: labels.empty_text,
    },
    editor: {
      addTitle: labels.editor_add_title,
      editTitle: labels.editor_edit_title,
      editTitleWithName: labels.editor_edit_title_with_name,
      createButton: labels.editor_create_button,
      saveButton: labels.editor_save_button,
      firstName: labels.editor_first_name,
      lastName: labels.editor_last_name,
      email: labels.editor_email,
      company: labels.editor_company,
      roles: labels.editor_roles,
      rolesPlaceholder: labels.editor_roles_placeholder,
      changePassword: labels.editor_change_password,
      createPasswordHint: labels.editor_create_password_hint,
      authOnlyHint: labels.editor_auth_only_hint,
      selfRoleHint: labels.editor_self_role_hint,
    },
    history: {
      title: labels.history_title,
      titleWithName: labels.history_title_with_name,
      loading: labels.history_loading,
      empty: labels.history_empty,
      errorTitle: labels.history_error_title,
    },
    actions: {
      edit: labels.action_edit_label,
      editDisabled: labels.action_edit_disabled_label,
      history: labels.action_history_label,
      delete: labels.action_delete_label,
    },
    confirm: {
      deleteTitle: labels.delete_confirm_title,
      deleteSelf: labels.delete_confirm_self,
      deleteMedusa: labels.delete_confirm_medusa,
      deleteShared: labels.delete_confirm_shared,
      deleteIrreversible: labels.delete_confirm_irreversible,
      ok: labels.delete_ok_label,
      cancel: labels.delete_cancel_label,
    },
    feedback: {
      loadUsers: labels.feedback_load_users,
      loadHistory: labels.feedback_load_history,
      updateUser: labels.feedback_update_user,
      deleteUser: labels.feedback_delete_user,
      saveUser: labels.feedback_save_user,
      createUser: labels.feedback_create_user,
      updateUserGeneric: labels.feedback_update_user_generic,
      deleteUserGeneric: labels.feedback_delete_user_generic,
    },
  };
}
