import "server-only";

import {
  PHI_TR_CTX_WEB_UI_LABEL,
  type PhiGlobalTranslatorOptions,
} from "../../../gateway/tr";
import { definePhiLabelSet, getPhiLabelSet } from "../../../gateway/label-set";
import {
  PHI_BACKGROUND_WIDGET_DEFAULT_LABELS,
  type PhiBackgroundWidgetLabels,
} from "../label-types/background";

const PHI_BACKGROUND_WIDGET_LABEL_SET = definePhiLabelSet({
  key: "widget:background",
  ctx: PHI_TR_CTX_WEB_UI_LABEL,
  labels: {
    title: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.title,
    description: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.description,
    section_base: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.sections.base,
    section_image: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.sections.image,
    section_gradient: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.sections.gradient,
    section_overlay: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.sections.overlay,
    section_effect: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.sections.effect,
    section_motion: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.sections.motion,
    base_none: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.base.none,
    base_color: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.base.color,
    base_gradient: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.base.gradient,
    base_image: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.base.image,
    image_url: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.image.url,
    image_alt: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.image.alt,
    image_position: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.image.position,
    image_size: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.image.size,
    image_repeat: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.image.repeat,
    motion_static: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.motion.static,
    motion_fixed: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.motion.fixed,
    motion_parallax: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.motion.parallax,
    motion_strength: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.motion.strength,
    motion_direction: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.motion.direction,
    motion_natural: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.motion.natural,
    motion_reverse: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.motion.reverse,
    motion_travel: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.motion.travel,
    motion_rate: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.motion.rate,
    motion_range: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.motion.range,
    motion_uses_original: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.motion.usesOriginal,
    gradient_direction: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.gradient.direction,
    gradient_stops: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.gradient.stops,
    gradient_add_stop: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.gradient.addStop,
    gradient_remove_stop: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.gradient.removeStop,
    overlay_none: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.none,
    overlay_pattern: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.pattern,
    overlay_noise: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.noise,
    overlay_grain: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.grain,
    overlay_opacity: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.opacity,
    overlay_direction: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.direction,
    overlay_scale: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.scale,
    overlay_pattern_stripes: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.patterns.stripes,
    overlay_pattern_grid: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.patterns.grid,
    overlay_pattern_dots: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.patterns.dots,
    overlay_pattern_checker: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.patterns.checker,
    overlay_pattern_crosshatch: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.patterns.crosshatch,
    overlay_grain_fine: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.grains.fine,
    overlay_grain_medium: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.grains.medium,
    overlay_grain_coarse: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.overlay.grains.coarse,
    effect_none: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.effect.none,
    effect_glass: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.effect.glass,
    effect_blur: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.effect.blur,
    effect_dim: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.effect.dim,
    effect_tint: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.effect.tint,
    direction_up: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.direction.up,
    direction_right: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.direction.right,
    direction_down: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.direction.down,
    direction_left: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.direction.left,
    position_center: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.position.center,
    position_top: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.position.top,
    position_bottom: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.position.bottom,
    position_left: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.position.left,
    position_right: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.position.right,
    position_top_left: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.position.topLeft,
    position_top_right: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.position.topRight,
    position_bottom_left: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.position.bottomLeft,
    position_bottom_right: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.position.bottomRight,
    size_cover: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.size.cover,
    size_contain: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.size.contain,
    size_auto: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.size.auto,
    repeat_no_repeat: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.repeat.noRepeat,
    repeat_repeat: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.repeat.repeat,
    repeat_repeat_x: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.repeat.repeatX,
    repeat_repeat_y: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.repeat.repeatY,
    common_none: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.common.none,
    common_opacity: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.common.opacity,
    common_scale: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.common.scale,
    common_direction: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.common.direction,
    placeholder_color_hex: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.placeholders.colorHex,
    placeholder_source_url: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.placeholders.sourceUrl,
    placeholder_source_alt: PHI_BACKGROUND_WIDGET_DEFAULT_LABELS.placeholders.sourceAlt,
  },
});

export async function getPhiBackgroundWidgetLabels(options: PhiGlobalTranslatorOptions): Promise<PhiBackgroundWidgetLabels> {
  const labels = await getPhiLabelSet(options, PHI_BACKGROUND_WIDGET_LABEL_SET);
  return {
    title: labels.title,
    description: labels.description,
    sections: {
      base: labels.section_base,
      image: labels.section_image,
      gradient: labels.section_gradient,
      overlay: labels.section_overlay,
      effect: labels.section_effect,
      motion: labels.section_motion,
    },
    base: {
      none: labels.base_none,
      color: labels.base_color,
      gradient: labels.base_gradient,
      image: labels.base_image,
    },
    image: {
      url: labels.image_url,
      alt: labels.image_alt,
      position: labels.image_position,
      size: labels.image_size,
      repeat: labels.image_repeat,
    },
    motion: {
      static: labels.motion_static,
      fixed: labels.motion_fixed,
      parallax: labels.motion_parallax,
      strength: labels.motion_strength,
      direction: labels.motion_direction,
      natural: labels.motion_natural,
      reverse: labels.motion_reverse,
      travel: labels.motion_travel,
      rate: labels.motion_rate,
      range: labels.motion_range,
      usesOriginal: labels.motion_uses_original,
    },
    gradient: {
      direction: labels.gradient_direction,
      stops: labels.gradient_stops,
      addStop: labels.gradient_add_stop,
      removeStop: labels.gradient_remove_stop,
    },
    overlay: {
      none: labels.overlay_none,
      pattern: labels.overlay_pattern,
      noise: labels.overlay_noise,
      grain: labels.overlay_grain,
      opacity: labels.overlay_opacity,
      direction: labels.overlay_direction,
      scale: labels.overlay_scale,
      patterns: {
        stripes: labels.overlay_pattern_stripes,
        grid: labels.overlay_pattern_grid,
        dots: labels.overlay_pattern_dots,
        checker: labels.overlay_pattern_checker,
        crosshatch: labels.overlay_pattern_crosshatch,
      },
      grains: {
        fine: labels.overlay_grain_fine,
        medium: labels.overlay_grain_medium,
        coarse: labels.overlay_grain_coarse,
      },
    },
    effect: {
      none: labels.effect_none,
      glass: labels.effect_glass,
      blur: labels.effect_blur,
      dim: labels.effect_dim,
      tint: labels.effect_tint,
    },
    direction: {
      up: labels.direction_up,
      right: labels.direction_right,
      down: labels.direction_down,
      left: labels.direction_left,
    },
    position: {
      center: labels.position_center,
      top: labels.position_top,
      bottom: labels.position_bottom,
      left: labels.position_left,
      right: labels.position_right,
      topLeft: labels.position_top_left,
      topRight: labels.position_top_right,
      bottomLeft: labels.position_bottom_left,
      bottomRight: labels.position_bottom_right,
    },
    size: {
      cover: labels.size_cover,
      contain: labels.size_contain,
      auto: labels.size_auto,
    },
    repeat: {
      noRepeat: labels.repeat_no_repeat,
      repeat: labels.repeat_repeat,
      repeatX: labels.repeat_repeat_x,
      repeatY: labels.repeat_repeat_y,
    },
    common: {
      none: labels.common_none,
      opacity: labels.common_opacity,
      scale: labels.common_scale,
      direction: labels.common_direction,
    },
    placeholders: {
      colorHex: labels.placeholder_color_hex,
      sourceUrl: labels.placeholder_source_url,
      sourceAlt: labels.placeholder_source_alt,
    },
  };
}
