import "server-only";

import {
  PHI_TR_CTX_WEB_UI_LABEL,
  type PhiGlobalTranslatorOptions,
} from "../../../gateway/tr";
import { definePhiLabelSet, getPhiLabelSet } from "../../../gateway/label-set";
import {
  PHI_EFFECTS_WIDGET_DEFAULT_LABELS,
  type PhiEffectsWidgetLabels,
} from "../label-types/effects";

const PHI_EFFECTS_WIDGET_LABEL_SET = definePhiLabelSet({
  key: "widget:effects",
  ctx: PHI_TR_CTX_WEB_UI_LABEL,
  labels: {
    modal_title: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.modalTitle,
    open_editor: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.openEditor,
    add: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.add,
    cancel: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.cancel,
    save: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.save,
    remove_transition: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.removeTransition,
    remove_viewport_effect: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.removeViewportEffect,
    section_transparency: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.sections.transparency,
    section_transitions: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.sections.transitions,
    section_viewport_effects: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.sections.viewportEffects,
    status_off: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.status.off,
    status_configured: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.status.configured,
    status_configured_plural: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.status.configuredPlural,
    field_amount: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.amount,
    field_trigger: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.trigger,
    field_once: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.once,
    field_type: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.type,
    field_mode: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.mode,
    field_duration: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.duration,
    field_delay: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.delay,
    field_direction: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.direction,
    field_distance: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.distance,
    field_axis: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.axis,
    field_angle: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.angle,
    field_perspective: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.perspective,
    field_origin: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.origin,
    field_scale: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.scale,
    field_easing: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.easing,
    field_property: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.property,
    field_from: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.from,
    field_to: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.to,
    field_unit: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.unit,
    field_clamp: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.clamp,
    field_range_start: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.rangeStart,
    field_range_end: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.fields.rangeEnd,
    table_number: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.table.number,
    table_transition: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.table.transition,
    table_trigger: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.table.trigger,
    table_viewport_effect: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.table.viewportEffect,
    table_empty_transitions: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.table.emptyTransitions,
    table_empty_viewport_effects: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.table.emptyViewportEffects,
    transition_fade: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.transitions.fade,
    transition_slide: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.transitions.slide,
    transition_flip: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.transitions.flip,
    transition_rotate: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.transitions.rotate,
    transition_scale: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.transitions.scale,
    transition_in: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.transitions.in,
    transition_out: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.transitions.out,
    transition_on_mount: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.transitions.onMount,
    transition_on_visible: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.transitions.onVisible,
    transition_on_hover: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.transitions.onHover,
    transition_on_focus: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.transitions.onFocus,
    transition_manual: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.transitions.manual,
    direction_top: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.directions.top,
    direction_top_right: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.directions.topRight,
    direction_right: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.directions.right,
    direction_bottom_right: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.directions.bottomRight,
    direction_bottom: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.directions.bottom,
    direction_bottom_left: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.directions.bottomLeft,
    direction_left: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.directions.left,
    direction_top_left: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.directions.topLeft,
    origin_top_left: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.origins.topLeft,
    origin_top_center: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.origins.topCenter,
    origin_top_right: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.origins.topRight,
    origin_center_left: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.origins.centerLeft,
    origin_center: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.origins.center,
    origin_center_right: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.origins.centerRight,
    origin_bottom_left: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.origins.bottomLeft,
    origin_bottom_center: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.origins.bottomCenter,
    origin_bottom_right: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.origins.bottomRight,
    viewport_x: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.viewport.x,
    viewport_y: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.viewport.y,
    viewport_translate: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.viewport.translate,
    viewport_opacity: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.viewport.opacity,
    viewport_rotate: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.viewport.rotate,
    viewport_scale: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.viewport.scale,
    viewport_enter: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.viewport.enter,
    viewport_center: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.viewport.center,
    viewport_exit: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.viewport.exit,
    viewport_unit_none: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.viewport.unitNone,
    easing_linear: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.easing.linear,
    easing_ease: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.easing.ease,
    easing_ease_in: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.easing.easeIn,
    easing_ease_out: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.easing.easeOut,
    easing_ease_in_out: PHI_EFFECTS_WIDGET_DEFAULT_LABELS.easing.easeInOut,
  },
});

export async function getPhiEffectsWidgetLabels(options: PhiGlobalTranslatorOptions): Promise<PhiEffectsWidgetLabels> {
  const labels = await getPhiLabelSet(options, PHI_EFFECTS_WIDGET_LABEL_SET);
  return {
    modalTitle: labels.modal_title,
    openEditor: labels.open_editor,
    add: labels.add,
    cancel: labels.cancel,
    save: labels.save,
    removeTransition: labels.remove_transition,
    removeViewportEffect: labels.remove_viewport_effect,
    sections: {
      transparency: labels.section_transparency,
      transitions: labels.section_transitions,
      viewportEffects: labels.section_viewport_effects,
    },
    status: {
      off: labels.status_off,
      configured: labels.status_configured,
      configuredPlural: labels.status_configured_plural,
    },
    fields: {
      amount: labels.field_amount,
      trigger: labels.field_trigger,
      once: labels.field_once,
      type: labels.field_type,
      mode: labels.field_mode,
      duration: labels.field_duration,
      delay: labels.field_delay,
      direction: labels.field_direction,
      distance: labels.field_distance,
      axis: labels.field_axis,
      angle: labels.field_angle,
      perspective: labels.field_perspective,
      origin: labels.field_origin,
      scale: labels.field_scale,
      easing: labels.field_easing,
      property: labels.field_property,
      from: labels.field_from,
      to: labels.field_to,
      unit: labels.field_unit,
      clamp: labels.field_clamp,
      rangeStart: labels.field_range_start,
      rangeEnd: labels.field_range_end,
    },
    table: {
      number: labels.table_number,
      transition: labels.table_transition,
      trigger: labels.table_trigger,
      viewportEffect: labels.table_viewport_effect,
      emptyTransitions: labels.table_empty_transitions,
      emptyViewportEffects: labels.table_empty_viewport_effects,
    },
    transitions: {
      fade: labels.transition_fade,
      slide: labels.transition_slide,
      flip: labels.transition_flip,
      rotate: labels.transition_rotate,
      scale: labels.transition_scale,
      in: labels.transition_in,
      out: labels.transition_out,
      onMount: labels.transition_on_mount,
      onVisible: labels.transition_on_visible,
      onHover: labels.transition_on_hover,
      onFocus: labels.transition_on_focus,
      manual: labels.transition_manual,
    },
    directions: {
      top: labels.direction_top,
      topRight: labels.direction_top_right,
      right: labels.direction_right,
      bottomRight: labels.direction_bottom_right,
      bottom: labels.direction_bottom,
      bottomLeft: labels.direction_bottom_left,
      left: labels.direction_left,
      topLeft: labels.direction_top_left,
    },
    origins: {
      topLeft: labels.origin_top_left,
      topCenter: labels.origin_top_center,
      topRight: labels.origin_top_right,
      centerLeft: labels.origin_center_left,
      center: labels.origin_center,
      centerRight: labels.origin_center_right,
      bottomLeft: labels.origin_bottom_left,
      bottomCenter: labels.origin_bottom_center,
      bottomRight: labels.origin_bottom_right,
    },
    viewport: {
      x: labels.viewport_x,
      y: labels.viewport_y,
      translate: labels.viewport_translate,
      opacity: labels.viewport_opacity,
      rotate: labels.viewport_rotate,
      scale: labels.viewport_scale,
      enter: labels.viewport_enter,
      center: labels.viewport_center,
      exit: labels.viewport_exit,
      unitNone: labels.viewport_unit_none,
    },
    easing: {
      linear: labels.easing_linear,
      ease: labels.easing_ease,
      easeIn: labels.easing_ease_in,
      easeOut: labels.easing_ease_out,
      easeInOut: labels.easing_ease_in_out,
    },
  };
}
