import "server-only";

import { PHI_TR_CTX_WEB_UI_LABEL, type PhiGlobalTranslatorOptions } from "../../../gateway/tr";
import { definePhiLabelSet, getPhiLabelSet } from "../../../gateway/label-set";
import {
  PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS,
  type PhiBuilderRevisionsWidgetLabels,
} from "../label-types/revisions";

const PHI_BUILDER_REVISIONS_WIDGET_LABEL_SET = definePhiLabelSet({
  key: "widget:builder-revisions",
  ctx: PHI_TR_CTX_WEB_UI_LABEL,
  labels: {
    kind_label: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.kindLabel,
    scope_label: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.scopeLabel,
    kind_area: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.kindOptions.area,
    kind_page: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.kindOptions.page,
    kind_navigation: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.kindOptions.navigation,
    kind_theme: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.kindOptions.theme,
    page_placeholder: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.pagePlaceholder,
    navigation_placeholder: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.navigationPlaceholder,
    theme_placeholder: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.themePlaceholder,
    revisions_label: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.revisionsLabel,
    selected_label: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.selectedLabel,
    system_label: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.systemLabel,
    published_label: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.publishedLabel,
    draft_label: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.draftLabel,
    deleted_label: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.deletedLabel,
    preset_update_label: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.presetUpdateLabel,
    message_fallback_from_revision: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.fallbackFromRevision,
    message_page_deleted: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.pageDeleted,
    message_page_meta_changed: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.pageMetaChanged,
    message_page_nodes_changed: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.pageNodesChanged,
    message_page_saved: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.pageSaved,
    message_area_nodes_changed: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.areaNodesChanged,
    message_area_saved: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.areaSaved,
    message_navigation_overlay_changed: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.navigationOverlayChanged,
    message_navigation_saved: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.navigationSaved,
    message_theme_changed: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.themeChanged,
    message_theme_saved: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.themeSaved,
    message_field_title: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.titleField,
    message_field_description: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.descriptionField,
    message_fields_title_and_description: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.messages.titleAndDescriptionFields,
    column_revision: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.columns.revision,
    column_created: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.columns.created,
    column_by: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.columns.by,
    column_message: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.columns.message,
    column_actions: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.columns.actions,
    action_review: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.actions.review,
    action_restore: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.actions.restore,
    action_delete: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.actions.delete,
    action_delete_selected: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.actions.deleteSelected,
    confirm_restore_title: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.confirm.restoreTitle,
    confirm_restore_description: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.confirm.restoreDescription,
    confirm_delete_title: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.confirm.deleteTitle,
    confirm_delete_description: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.confirm.deleteDescription,
    confirm_delete_selected_title: PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.confirm.deleteSelectedTitle,
    confirm_delete_selected_description:
      PHI_BUILDER_REVISIONS_WIDGET_DEFAULT_LABELS.confirm.deleteSelectedDescription,
  },
});

export async function getPhiBuilderRevisionsWidgetLabels(options: PhiGlobalTranslatorOptions): Promise<PhiBuilderRevisionsWidgetLabels> {
  const labels = await getPhiLabelSet(options, PHI_BUILDER_REVISIONS_WIDGET_LABEL_SET);
  return {
    kindLabel: labels.kind_label,
    scopeLabel: labels.scope_label,
    kindOptions: {
      area: labels.kind_area,
      page: labels.kind_page,
      navigation: labels.kind_navigation,
      theme: labels.kind_theme,
    },
    pagePlaceholder: labels.page_placeholder,
    navigationPlaceholder: labels.navigation_placeholder,
    themePlaceholder: labels.theme_placeholder,
    revisionsLabel: labels.revisions_label,
    selectedLabel: labels.selected_label,
    systemLabel: labels.system_label,
    publishedLabel: labels.published_label,
    draftLabel: labels.draft_label,
    deletedLabel: labels.deleted_label,
    presetUpdateLabel: labels.preset_update_label,
    messages: {
      fallbackFromRevision: labels.message_fallback_from_revision,
      pageDeleted: labels.message_page_deleted,
      pageMetaChanged: labels.message_page_meta_changed,
      pageNodesChanged: labels.message_page_nodes_changed,
      pageSaved: labels.message_page_saved,
      areaNodesChanged: labels.message_area_nodes_changed,
      areaSaved: labels.message_area_saved,
      navigationOverlayChanged: labels.message_navigation_overlay_changed,
      navigationSaved: labels.message_navigation_saved,
      themeChanged: labels.message_theme_changed,
      themeSaved: labels.message_theme_saved,
      titleField: labels.message_field_title,
      descriptionField: labels.message_field_description,
      titleAndDescriptionFields: labels.message_fields_title_and_description,
    },
    columns: {
      revision: labels.column_revision,
      created: labels.column_created,
      by: labels.column_by,
      message: labels.column_message,
      actions: labels.column_actions,
    },
    actions: {
      review: labels.action_review,
      restore: labels.action_restore,
      delete: labels.action_delete,
      deleteSelected: labels.action_delete_selected,
    },
    confirm: {
      restoreTitle: labels.confirm_restore_title,
      restoreDescription: labels.confirm_restore_description,
      deleteTitle: labels.confirm_delete_title,
      deleteDescription: labels.confirm_delete_description,
      deleteSelectedTitle: labels.confirm_delete_selected_title,
      deleteSelectedDescription: labels.confirm_delete_selected_description,
    },
  };
}
