import "server-only";

import {
  PHI_TR_CTX_WEB_UI_LABEL,
  type PhiGlobalTranslatorOptions,
} from "../../../gateway/tr";
import { definePhiLabelSet, getPhiLabelSet } from "../../../gateway/label-set";

const PHI_GROUPS_FORM_LABEL_SET = definePhiLabelSet({
  key: "@phis/ui/modules/groups/labels/forms",
  ctx: PHI_TR_CTX_WEB_UI_LABEL,
  labels: {
    create_title: "Create group",
    create_description: "A group is an authorization unit. Pages, Navigation, and Assets refer to it.",
    key_label: "Key",
    key_hint: "The stable identifier a Module or a Page refers to. It cannot be changed later.",
    key_required: "A key is required.",
    name_label: "Name",
    name_hint: "The name members see.",
    name_required: "A name is required.",
    submit_label: "Create group",
    page_title: "Groups",
    page_description: "Site groups, their members, and the Space each group shares.",
    groups_title: "Groups",
    groups_description: "A group is an authorization unit. Pages, Navigation, and Assets refer to it.",
    members_title: "Members",
    members_description: "Select a group to see who belongs to it.",
    members_empty: "No group selected.",
    column_name: "Name",
    column_key: "Key",
    column_members: "Members",
    column_source: "Source",
    column_space_used: "Space used",
    column_space_quota: "Space quota",
    column_email: "Email",
    column_level: "Level",
    column_since: "Member since",
    level_member: "Member",
    level_author: "Author",
    level_editor: "Editor",
    level_manager: "Manager",
    remove_label: "Remove from group",
    remove_confirm_title: "Remove this member?",
    remove_confirm_text: "They lose whatever the group grants them, on every Page and Asset that names it.",
    remove_confirm_ok: "Remove",
    remove_confirm_cancel: "Cancel",
    level_hint: "A Manager is a Contributor is a Member.",
    membership_title: "Add a member",
    membership_description: "Naming someone who is already a member changes their level.",
    membership_group_label: "Group",
    membership_group_required: "Choose a group.",
    membership_person_label: "Person",
    membership_person_required: "Choose a person.",
    membership_level_label: "Level",
    membership_level_required: "Choose a level.",
    membership_submit_label: "Add member",
    mine_title: "My groups",
    mine_description: "What each group lets you do, and how much of its shared space is in use.",
    mine_empty: "You are in no group yet.",
    mine_empty_hint: "A group is set up by an administrator; you will see it here once you are in one.",
    column_company: "Company",
    column_show_company: "Show company",
    column_show_company_hint: "Show each member's company to the other members of this group.",
    create_action_label: "Create group",
    refresh_label: "Refresh",
    column_state: "State",
    state_active: "In service",
    state_retired: "Retired",
    retire_label: "Retire group",
    retire_confirm_title: "Retire this group?",
    retire_confirm_text:
      "Its members lose whatever it grants them, and it disappears from group and Space selection. "
      + "Its name stays reserved and its shared space is kept, so an administrator can put it back.",
    retire_confirm_ok: "Retire",
    reactivate_label: "Put back in service",
    reactivate_confirm_title: "Put this group back in service?",
    reactivate_confirm_text: "Its members get back everything it grants, on every Page and Asset that names it.",
    reactivate_confirm_ok: "Reactivate",
  },
});

export async function getPhiGroupFormLabels(options: PhiGlobalTranslatorOptions) {
  const labels = await getPhiLabelSet(options, PHI_GROUPS_FORM_LABEL_SET);
  return {
    create: {
      title: labels.create_title,
      description: labels.create_description,
    },
    fields: {
      key: labels.key_label,
      keyHint: labels.key_hint,
      keyRequired: labels.key_required,
      name: labels.name_label,
      nameHint: labels.name_hint,
      nameRequired: labels.name_required,
    },
    submitLabel: labels.submit_label,
    page: {
      title: labels.page_title,
      description: labels.page_description,
    },
    groups: {
      title: labels.groups_title,
      description: labels.groups_description,
    },
    members: {
      title: labels.members_title,
      description: labels.members_description,
      empty: labels.members_empty,
    },
    columns: {
      name: labels.column_name,
      key: labels.column_key,
      members: labels.column_members,
      source: labels.column_source,
      spaceUsed: labels.column_space_used,
      spaceQuota: labels.column_space_quota,
      email: labels.column_email,
      level: labels.column_level,
      since: labels.column_since,
      company: labels.column_company,
      showCompany: labels.column_show_company,
      showCompanyHint: labels.column_show_company_hint,
      state: labels.column_state,
    },
    states: {
      active: labels.state_active,
      retired: labels.state_retired,
    },
    levels: {
      member: labels.level_member,
      author: labels.level_author,
      editor: labels.level_editor,
      manager: labels.level_manager,
    },
    mine: {
      title: labels.mine_title,
      description: labels.mine_description,
      empty: labels.mine_empty,
      emptyHint: labels.mine_empty_hint,
    },
    membership: {
      title: labels.membership_title,
      description: labels.membership_description,
      group: labels.membership_group_label,
      groupRequired: labels.membership_group_required,
      person: labels.membership_person_label,
      personRequired: labels.membership_person_required,
      level: labels.membership_level_label,
      levelRequired: labels.membership_level_required,
      submit: labels.membership_submit_label,
    },
    actions: {
      remove: labels.remove_label,
      removeConfirmTitle: labels.remove_confirm_title,
      removeConfirmText: labels.remove_confirm_text,
      removeConfirmOk: labels.remove_confirm_ok,
      removeConfirmCancel: labels.remove_confirm_cancel,
      levelHint: labels.level_hint,
      create: labels.create_action_label,
      refresh: labels.refresh_label,
      retire: labels.retire_label,
      retireConfirmTitle: labels.retire_confirm_title,
      retireConfirmText: labels.retire_confirm_text,
      retireConfirmOk: labels.retire_confirm_ok,
      reactivate: labels.reactivate_label,
      reactivateConfirmTitle: labels.reactivate_confirm_title,
      reactivateConfirmText: labels.reactivate_confirm_text,
      reactivateConfirmOk: labels.reactivate_confirm_ok,
    },
  };
}
