import "server-only";

import { definePhiLabelSet, getPhiLabelSet } from "../../../gateway/label-set";
import {
  PHI_TR_CTX_WEB_UI_LABEL,
  type PhiGlobalTranslatorOptions,
} from "../../../gateway/tr";
import {
  PHI_MEDIA_WIDGET_DEFAULT_LABELS,
  type PhiAssetWidgetLabels,
} from "../media-widget-labels";

const PHI_MEDIA_WIDGET_LABEL_SET = definePhiLabelSet({
  key: "widget:media",
  ctx: PHI_TR_CTX_WEB_UI_LABEL,
  labels: {
    tool_search_placeholder: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.searchPlaceholder,
    tool_folder_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.folderLabel,
    tool_create_folder_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.createFolderLabel,
    tool_flags_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.flagsLabel,
    tool_flag_placeholder: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.flagPlaceholder,
    tool_upload_toggle_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.uploadToggleLabel,
    tool_kind_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.kindLabel,
    tool_reset_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.resetLabel,
    tool_reload_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.reloadLabel,
    tool_assets_template: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.assetsTemplate,
    tool_image_kind_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.imageKindLabel,
    tool_video_kind_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.videoKindLabel,
    tool_audio_kind_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.audioKindLabel,
    tool_pdf_kind_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.pdfKindLabel,
    tool_markdown_kind_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.markdownKindLabel,
    tool_document_kind_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.documentKindLabel,
    tool_archive_kind_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.archiveKindLabel,
    tool_binary_kind_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.binaryKindLabel,
    tool_other_kind_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.tool.otherKindLabel,
    upload_drop_title: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.dropTitle,
    upload_drop_hint: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.dropHint,
    upload_upload_toggle_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.uploadToggleLabel,
    upload_retry_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.retryLabel,
    upload_delete_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.deleteLabel,
    upload_done_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.doneLabel,
    upload_failed_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.failedLabel,
    upload_asset_exists_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.assetExistsLabel,
    upload_delete_success_template: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.deleteSuccessTemplate,
    upload_upload_success_template: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.uploadSuccessTemplate,
    upload_upload_failed_text: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.uploadFailedText,
    upload_storage_unreachable_text: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.uploadStorageUnreachableText,
    upload_delete_failed_text: PHI_MEDIA_WIDGET_DEFAULT_LABELS.upload.deleteFailedText,
    grid_empty_description: PHI_MEDIA_WIDGET_DEFAULT_LABELS.grid.emptyDescription,
    grid_delete_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.grid.deleteLabel,
    grid_delete_success_template: PHI_MEDIA_WIDGET_DEFAULT_LABELS.grid.deleteSuccessTemplate,
    grid_delete_failed_text: PHI_MEDIA_WIDGET_DEFAULT_LABELS.grid.deleteFailedText,
    inspector_inspector_title: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.inspectorTitle,
    inspector_preview_title: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.previewTitle,
    inspector_metadata_title: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.metadataTitle,
    inspector_variants_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.variantsLabel,
    inspector_original_variant_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.originalVariantLabel,
    inspector_thumbnail_variant_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.thumbnailVariantLabel,
    inspector_preview_variant_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.previewVariantLabel,
    inspector_banner_variant_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.bannerVariantLabel,
    inspector_header_variant_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.headerVariantLabel,
    inspector_card_variant_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.cardVariantLabel,
    inspector_hero_variant_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.heroVariantLabel,
    inspector_avatar_variant_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.avatarVariantLabel,
    inspector_logo_variant_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.logoVariantLabel,
    inspector_landscape_variant_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.landscapeVariantLabel,
    inspector_portrait_variant_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.portraitVariantLabel,
    inspector_storage_key_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.storageKeyLabel,
    inspector_public_url_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.publicUrlLabel,
    inspector_content_type_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.contentTypeLabel,
    inspector_original_name_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.originalNameLabel,
    inspector_restricted_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.restrictedLabel,
    inspector_copy_label_template: PHI_MEDIA_WIDGET_DEFAULT_LABELS.inspector.copyLabelTemplate,
    editor_title_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.titleLabel,
    editor_alt_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.altLabel,
    editor_folder_path_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.folderPathLabel,
    editor_folder_path_placeholder: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.folderPathPlaceholder,
    editor_folder_path_help: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.folderPathHelp,
    editor_create_folder_title: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.createFolderTitle,
    editor_folder_name_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.folderNameLabel,
    editor_folder_name_placeholder: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.folderNamePlaceholder,
    editor_folder_name_required: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.folderNameRequired,
    editor_parent_folder_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.parentFolderLabel,
    editor_top_level_folder_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.topLevelFolderLabel,
    editor_flags_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.flagsLabel,
    editor_focal_rect_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.focalRectLabel,
    editor_focal_rect_button_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.focalRectButtonLabel,
    editor_focal_rect_save_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.focalRectSaveLabel,
    editor_focal_rect_reset_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.focalRectResetLabel,
    editor_focal_rect_clear_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.focalRectClearLabel,
    editor_focal_rect_help_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.focalRectHelpLabel,
    editor_save_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.saveLabel,
    editor_saving_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.savingLabel,
    editor_save_success_text: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.saveSuccessText,
    editor_save_failed_text: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.saveFailedText,
    editor_private_flag_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.privateFlagLabel,
    editor_archived_flag_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.archivedFlagLabel,
    editor_download_flag_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.downloadFlagLabel,
    editor_featured_flag_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.featuredFlagLabel,
    editor_locked_flag_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.lockedFlagLabel,
    editor_mask_flag_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.editor.maskFlagLabel,
    picker_trigger_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.picker.triggerLabel,
    picker_popover_title: PHI_MEDIA_WIDGET_DEFAULT_LABELS.picker.popoverTitle,
    picker_selected_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.picker.selectedLabel,
    picker_empty_description: PHI_MEDIA_WIDGET_DEFAULT_LABELS.picker.emptyDescription,
    picker_clear_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.picker.clearLabel,
    picker_tile_size_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.picker.tileSizeLabel,
    space_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.space.label,
    space_site_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.space.site,
    space_user_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.space.user,
    space_group_label: PHI_MEDIA_WIDGET_DEFAULT_LABELS.space.group,
  },
});

export async function getPhiMediaWidgetLabels(
  options: PhiGlobalTranslatorOptions,
): Promise<PhiAssetWidgetLabels> {
  const labels = await getPhiLabelSet(options, PHI_MEDIA_WIDGET_LABEL_SET);
  return {
    tool: {
      searchPlaceholder: labels.tool_search_placeholder,
      folderLabel: labels.tool_folder_label,
      createFolderLabel: labels.tool_create_folder_label,
      flagsLabel: labels.tool_flags_label,
      flagPlaceholder: labels.tool_flag_placeholder,
      uploadToggleLabel: labels.tool_upload_toggle_label,
      kindLabel: labels.tool_kind_label,
      resetLabel: labels.tool_reset_label,
      reloadLabel: labels.tool_reload_label,
      assetsTemplate: labels.tool_assets_template,
      imageKindLabel: labels.tool_image_kind_label,
      videoKindLabel: labels.tool_video_kind_label,
      audioKindLabel: labels.tool_audio_kind_label,
      pdfKindLabel: labels.tool_pdf_kind_label,
      markdownKindLabel: labels.tool_markdown_kind_label,
      documentKindLabel: labels.tool_document_kind_label,
      archiveKindLabel: labels.tool_archive_kind_label,
      binaryKindLabel: labels.tool_binary_kind_label,
      otherKindLabel: labels.tool_other_kind_label,
    },
    upload: {
      dropTitle: labels.upload_drop_title,
      dropHint: labels.upload_drop_hint,
      uploadToggleLabel: labels.upload_upload_toggle_label,
      retryLabel: labels.upload_retry_label,
      deleteLabel: labels.upload_delete_label,
      doneLabel: labels.upload_done_label,
      failedLabel: labels.upload_failed_label,
      assetExistsLabel: labels.upload_asset_exists_label,
      deleteSuccessTemplate: labels.upload_delete_success_template,
      uploadSuccessTemplate: labels.upload_upload_success_template,
      uploadFailedText: labels.upload_upload_failed_text,
      uploadStorageUnreachableText: labels.upload_storage_unreachable_text,
      deleteFailedText: labels.upload_delete_failed_text,
    },
    grid: {
      emptyDescription: labels.grid_empty_description,
      deleteLabel: labels.grid_delete_label,
      deleteSuccessTemplate: labels.grid_delete_success_template,
      deleteFailedText: labels.grid_delete_failed_text,
    },
    inspector: {
      inspectorTitle: labels.inspector_inspector_title,
      previewTitle: labels.inspector_preview_title,
      metadataTitle: labels.inspector_metadata_title,
      variantsLabel: labels.inspector_variants_label,
      originalVariantLabel: labels.inspector_original_variant_label,
      thumbnailVariantLabel: labels.inspector_thumbnail_variant_label,
      previewVariantLabel: labels.inspector_preview_variant_label,
      bannerVariantLabel: labels.inspector_banner_variant_label,
      headerVariantLabel: labels.inspector_header_variant_label,
      cardVariantLabel: labels.inspector_card_variant_label,
      heroVariantLabel: labels.inspector_hero_variant_label,
      avatarVariantLabel: labels.inspector_avatar_variant_label,
      logoVariantLabel: labels.inspector_logo_variant_label,
      landscapeVariantLabel: labels.inspector_landscape_variant_label,
      portraitVariantLabel: labels.inspector_portrait_variant_label,
      storageKeyLabel: labels.inspector_storage_key_label,
      publicUrlLabel: labels.inspector_public_url_label,
      contentTypeLabel: labels.inspector_content_type_label,
      originalNameLabel: labels.inspector_original_name_label,
      restrictedLabel: labels.inspector_restricted_label,
      copyLabelTemplate: labels.inspector_copy_label_template,
    },
    editor: {
      titleLabel: labels.editor_title_label,
      altLabel: labels.editor_alt_label,
      folderPathLabel: labels.editor_folder_path_label,
      folderPathPlaceholder: labels.editor_folder_path_placeholder,
      folderPathHelp: labels.editor_folder_path_help,
      createFolderTitle: labels.editor_create_folder_title,
      folderNameLabel: labels.editor_folder_name_label,
      folderNamePlaceholder: labels.editor_folder_name_placeholder,
      folderNameRequired: labels.editor_folder_name_required,
      parentFolderLabel: labels.editor_parent_folder_label,
      topLevelFolderLabel: labels.editor_top_level_folder_label,
      flagsLabel: labels.editor_flags_label,
      focalRectLabel: labels.editor_focal_rect_label,
      focalRectButtonLabel: labels.editor_focal_rect_button_label,
      focalRectSaveLabel: labels.editor_focal_rect_save_label,
      focalRectResetLabel: labels.editor_focal_rect_reset_label,
      focalRectClearLabel: labels.editor_focal_rect_clear_label,
      focalRectHelpLabel: labels.editor_focal_rect_help_label,
      saveLabel: labels.editor_save_label,
      savingLabel: labels.editor_saving_label,
      saveSuccessText: labels.editor_save_success_text,
      saveFailedText: labels.editor_save_failed_text,
      privateFlagLabel: labels.editor_private_flag_label,
      archivedFlagLabel: labels.editor_archived_flag_label,
      downloadFlagLabel: labels.editor_download_flag_label,
      featuredFlagLabel: labels.editor_featured_flag_label,
      lockedFlagLabel: labels.editor_locked_flag_label,
      maskFlagLabel: labels.editor_mask_flag_label,
    },
    picker: {
      triggerLabel: labels.picker_trigger_label,
      popoverTitle: labels.picker_popover_title,
      selectedLabel: labels.picker_selected_label,
      emptyDescription: labels.picker_empty_description,
      clearLabel: labels.picker_clear_label,
      tileSizeLabel: labels.picker_tile_size_label,
    },
    space: {
      label: labels.space_label,
      site: labels.space_site_label,
      user: labels.space_user_label,
      group: labels.space_group_label,
    },
  };
}
