import type { PhiRuntimeModuleDataProviderDescriptor } from "../contracts";
import { PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS } from "./ids";
import { PHI_BUILDER_RUNTIME_MODULE_ID } from "./ids";
import { PHI_BUILDER_AREA_OPTIONS } from "../../../constants/cms-areas";
import { PHI_BUILDER_NAVIGATION_DND_TYPE_PAGE } from "../../../constants/builder-navigation-dnd";

export const PHI_BUILDER_RUNTIME_DATA_PROVIDER_DESCRIPTORS = [
  {
    key: PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS.builderPages,
    ownerModuleId: PHI_BUILDER_RUNTIME_MODULE_ID,
    kind: "options",
    executionMode: "live",
    authoringMode: "none",
    title: "Builder pages",
    description: "Builder page catalog choices for the active target area.",
  },
  {
    key: PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS.signalSenders,
    ownerModuleId: PHI_BUILDER_RUNTIME_MODULE_ID,
    kind: "options",
    executionMode: "live",
    authoringMode: "none",
    title: "Signal senders",
    description: "Endpoints of the selected block that can emit.",
  },
  {
    key: PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS.signalSenderCapabilities,
    ownerModuleId: PHI_BUILDER_RUNTIME_MODULE_ID,
    kind: "options",
    executionMode: "live",
    authoringMode: "none",
    title: "Signal sender outputs",
    description: "Outputs of the chosen sender endpoint.",
  },
  {
    key: PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS.signalReceivers,
    ownerModuleId: PHI_BUILDER_RUNTIME_MODULE_ID,
    kind: "options",
    executionMode: "live",
    authoringMode: "none",
    title: "Signal receivers",
    description: "Endpoints in the Area that can receive the chosen output.",
  },
  {
    key: PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS.signalReceiverCapabilities,
    ownerModuleId: PHI_BUILDER_RUNTIME_MODULE_ID,
    kind: "options",
    executionMode: "live",
    authoringMode: "none",
    title: "Signal receiver inputs",
    description: "Inputs of the chosen receiver that match the chosen output.",
  },
  {
    key: PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS.pageSourceTree,
    ownerModuleId: PHI_BUILDER_RUNTIME_MODULE_ID,
    kind: "tree",
    executionMode: "live",
    authoringMode: "read",
    title: "Builder page source tree",
    description: "Hierarchical page catalog for navigation authoring drag sources.",
    resources: [{
      resourceKey: "pages",
      title: "Pages",
      nodeIdentityPath: "id",
      parentNodeIdentityPath: "parentId",
      titleFieldKey: "title",
      descriptionFieldKey: "path",
      fields: [
        { key: "id", title: "ID", type: "string", required: true },
        { key: "parentId", title: "Parent", type: "string" },
        { key: "title", title: "Title", type: "string", required: true },
        { key: "path", title: "Path", type: "string", required: true },
        { key: "dragIdentity", title: "Drag identity", type: "string", required: true },
      ],
      bindingFields: [{
        key: "area",
        title: "Area",
        type: "enum",
        required: true,
        options: PHI_BUILDER_AREA_OPTIONS,
      }],
      query: { search: true },
      nodeOrdering: "none",
      dragSources: [{
        payloadType: PHI_BUILDER_NAVIGATION_DND_TYPE_PAGE,
        sourceObjectIdentityPath: "dragIdentity",
      }],
    }],
  },
  {
    key: PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS.builderNavigationSets,
    ownerModuleId: PHI_BUILDER_RUNTIME_MODULE_ID,
    kind: "options",
    executionMode: "static",
    authoringMode: "read",
    title: "Builder navigation sets",
    description: "Navigation set choices for the active Builder area.",
  },
  {
    key: PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS.forms,
    ownerModuleId: PHI_BUILDER_RUNTIME_MODULE_ID,
    kind: "options",
    executionMode: "static",
    authoringMode: "read",
    title: "Forms",
    description: "Preset Forms contributed by the active target-Area modules.",
  },
  {
    key: PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS.runtimeModules,
    ownerModuleId: PHI_BUILDER_RUNTIME_MODULE_ID,
    kind: "options",
    executionMode: "live",
    authoringMode: "none",
    title: "Runtime modules",
    description: "Installed optional runtime modules available for area activation.",
  },
  {
    key: PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS.navigationTable,
    ownerModuleId: PHI_BUILDER_RUNTIME_MODULE_ID,
    kind: "table",
    executionMode: "live",
    authoringMode: "edit",
    title: "Builder navigation",
    description: "Editable Navigation Draft items for the active Builder navigation scope.",
    resources: [{
      resourceKey: "navigationItems",
      title: "Navigation items",
      rowIdentityPath: "id",
      bindingFields: [{
        key: "navKey",
        title: "Navigation",
        type: "enum",
        required: true,
        optionsProvider: {
          providerKey: PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS.builderNavigationSets,
          params: { value: "scopeKey" },
        },
        create: { actionKey: "create-navigation" },
      }],
      fields: [
        { key: "id", title: "ID", type: "string", required: true },
        { key: "parentId", title: "Parent", type: "string" },
        { key: "canAcceptChildren", title: "Accepts children", type: "boolean", required: true },
        {
          key: "icon",
          title: "Icon",
          type: "icon",
          mutable: true,
        },
        {
          key: "label",
          title: "Label",
          type: "string",
          required: true,
          mutable: true,
        },
        { key: "navigationType", title: "Type", type: "enum", required: true, options: [
          { value: "link", label: "Link" },
          { value: "external", label: "External" },
          { value: "container", label: "Container" },
          { value: "separator", label: "Separator" },
        ] },
        { key: "origin", title: "Origin", type: "string" },
        {
          key: "href",
          title: "Path",
          type: "string",
          mutable: true,
          mutableWhen: { match: "all", conditions: [
            { source: "row", valuePath: "source", operator: "equals", value: "custom" },
            { source: "row", valuePath: "navigationType", operator: "equals", value: "external" },
          ] },
        },
        { key: "source", title: "Source", type: "enum", options: [
          { value: "module", label: "Module" },
          { value: "custom", label: "Site" },
        ] },
        { key: "hidden", title: "Hidden", type: "boolean" },
        { key: "hiddenByAncestor", title: "Hidden by ancestor", type: "boolean" },
        { key: "external", title: "External", type: "boolean" },
        { key: "newTabEditable", title: "New tab editable", type: "boolean", required: true },
        {
          key: "newTab",
          title: "New tab",
          type: "boolean",
          mutable: true,
          mutableWhen: { match: "all", conditions: [
            { source: "row", valuePath: "newTabEditable", operator: "truthy" },
          ] },
        },
      ],
      summaryFields: [
        { key: "entries", title: "Entries", type: "number" },
        { key: "hidden", title: "Hidden", type: "number" },
      ],
      query: { sorting: "none", pagination: "none", expansion: true },
      actions: [
        { key: "create-navigation", title: "Create navigation", scope: "resource", valueType: "string", intent: "write" },
        { key: "add-link", title: "Add link", scope: "resource", intent: "write" },
        { key: "add-container", title: "Add container", scope: "resource", intent: "write" },
        { key: "add-separator", title: "Add separator", scope: "resource", intent: "write" },
        {
          key: "hide",
          title: "Hide",
          scope: "row",
          intent: "write",
          visibleWhen: { match: "all", conditions: [
            { source: "row", valuePath: "source", operator: "equals", value: "module" },
            { source: "row", valuePath: "hidden", operator: "falsy" },
          ] },
        },
        {
          key: "show",
          title: "Show",
          scope: "row",
          intent: "write",
          visibleWhen: { match: "all", conditions: [
            { source: "row", valuePath: "source", operator: "equals", value: "module" },
            { source: "row", valuePath: "hidden", operator: "truthy" },
          ] },
        },
        {
          key: "delete",
          title: "Delete",
          scope: "row",
          intent: "destructive",
          confirmation: "required",
          visibleWhen: { source: "row", valuePath: "source", operator: "equals", value: "custom" },
        },
      ],
      rowOrdering: "tree",
      hierarchy: { parentRowIdentityPath: "parentId", canAcceptChildrenField: "canAcceptChildren" },
      dropTargets: [{
        payloadType: "@phis/builder-navigation-page",
        modes: ["before", "after", "child", "append"],
      }],
    }],
  },
  {
    key: PHI_BUILDER_RUNTIME_DATA_PROVIDER_KEYS.signalRoutesTable,
    ownerModuleId: PHI_BUILDER_RUNTIME_MODULE_ID,
    kind: "table",
    executionMode: "live",
    authoringMode: "edit",
    title: "Builder signal routes",
    description: "Editable signal routes for the active Builder wiring session.",
    resources: [{
      resourceKey: "signalRoutes",
      title: "Signal routes",
      rowIdentityPath: "routeKey",
      fields: [
        { key: "routeKey", title: "Route key", type: "string", required: true },
        { key: "direction", title: "Direction", type: "string", required: true },
        { key: "capabilityId", title: "Capability", type: "string", required: true },
        { key: "scope", title: "Scope", type: "string", required: true },
        { key: "channel", title: "Channel", type: "string", required: true },
        { key: "action", title: "Action", type: "string", required: true },
        { key: "valueType", title: "Value type", type: "string", required: true },
        { key: "receiver", title: "Receiver", type: "string" },
      ],
      query: {
        search: true,
        filterFields: ["sessionKey", "direction"],
        sorting: "none",
        pagination: "offset",
      },
      actions: [
        { key: "save", title: "Save", scope: "row", valueType: "json" },
        { key: "edit", title: "Edit", scope: "row" },
        { key: "delete", title: "Delete", scope: "row" },
        { key: "cancel", title: "Cancel", scope: "resource" },
      ],
    }],
  },
] satisfies readonly PhiRuntimeModuleDataProviderDescriptor[];
