"use client";

import {
  ApartmentOutlined,
  ApiOutlined,
  AppstoreOutlined,
  BranchesOutlined,
  CheckOutlined,
  CloseOutlined,
  CodeOutlined,
  ColumnWidthOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DeleteOutlined,
  DownloadOutlined,
  EditOutlined,
  ExperimentOutlined,
  FileTextOutlined,
  HistoryOutlined,
  MenuOutlined,
  MessageOutlined,
  NotificationOutlined,
  PictureOutlined,
  PlusOutlined,
  ProfileOutlined,
  ReadOutlined,
  SafetyCertificateOutlined,
  SettingOutlined,
  SkinOutlined,
  TableOutlined,
  TeamOutlined,
  TranslationOutlined,
  UserAddOutlined,
} from "@ant-design/icons";

const PHI_MANAGEMENT_ICON_REGISTRY = {
  apartment: ApartmentOutlined,
  "apartment-outlined": ApartmentOutlined,
  api: ApiOutlined,
  "api-outlined": ApiOutlined,
  appstore: AppstoreOutlined,
  "appstore-outlined": AppstoreOutlined,
  branches: BranchesOutlined,
  "branches-outlined": BranchesOutlined,
  check: CheckOutlined,
  "check-outlined": CheckOutlined,
  close: CloseOutlined,
  "close-outlined": CloseOutlined,
  code: CodeOutlined,
  "code-outlined": CodeOutlined,
  "column-width": ColumnWidthOutlined,
  "column-width-outlined": ColumnWidthOutlined,
  "customer-service": CustomerServiceOutlined,
  "customer-service-outlined": CustomerServiceOutlined,
  dashboard: DashboardOutlined,
  "dashboard-outlined": DashboardOutlined,
  delete: DeleteOutlined,
  "delete-outlined": DeleteOutlined,
  edit: EditOutlined,
  "edit-outlined": EditOutlined,
  download: DownloadOutlined,
  "download-outlined": DownloadOutlined,
  experiment: ExperimentOutlined,
  "experiment-outlined": ExperimentOutlined,
  file: FileTextOutlined,
  "file-text": FileTextOutlined,
  "file-search": FileTextOutlined,
  "file-text-outlined": FileTextOutlined,
  history: HistoryOutlined,
  "history-outlined": HistoryOutlined,
  menu: MenuOutlined,
  "menu-outlined": MenuOutlined,
  message: MessageOutlined,
  "message-outlined": MessageOutlined,
  notification: NotificationOutlined,
  "notification-outlined": NotificationOutlined,
  picture: PictureOutlined,
  "picture-outlined": PictureOutlined,
  plus: PlusOutlined,
  "plus-outlined": PlusOutlined,
  profile: ProfileOutlined,
  "profile-outlined": ProfileOutlined,
  read: ReadOutlined,
  "read-outlined": ReadOutlined,
  "safety-certificate": SafetyCertificateOutlined,
  "safety-certificate-outlined": SafetyCertificateOutlined,
  setting: SettingOutlined,
  "setting-outlined": SettingOutlined,
  skin: SkinOutlined,
  "skin-outlined": SkinOutlined,
  table: TableOutlined,
  "table-outlined": TableOutlined,
  team: TeamOutlined,
  "team-outlined": TeamOutlined,
  translation: TranslationOutlined,
  "translation-outlined": TranslationOutlined,
  "user-add": UserAddOutlined,
  "user-add-outlined": UserAddOutlined,
} as const;

export function PhiManagementIcon({
  name,
  size,
}: {
  name: string;
  size: number | string;
}) {
  const Icon =
    PHI_MANAGEMENT_ICON_REGISTRY[
      name as keyof typeof PHI_MANAGEMENT_ICON_REGISTRY
    ];
  return Icon ? <Icon style={{ fontSize: size }} /> : null;
}
