import "server-only";

import {
  PHI_TR_CTX_WEB_UI_LABEL,
  type PhiGlobalTranslatorOptions,
} from "../../gateway/tr";
import { definePhiLabelSet, getPhiLabelSet } from "../../gateway/label-set";

const PHI_AUTH_ADMIN_SETTINGS_LABEL_SET = definePhiLabelSet({
  key: "preset:admin-auth-settings-page",
  ctx: PHI_TR_CTX_WEB_UI_LABEL,
  labels: {
    page_title: "Authentication",
    page_description: "Choose which login methods this site offers and how accounts are created and linked.",
    policy_title: "Registration and account linking",
    policy_description: "How new accounts are created and how sign-ins link to existing accounts.",
    password_title: "Password",
    password_description: "The built-in password login method.",
    totp_title: "Two-factor authentication",
    totp_description: "Authenticator-app requirement and enforcement for site members.",
    providers_title: "Identity providers",
    providers_description: "External login providers for this site. Secrets are write-only.",
    registration_mode_label: "Registration",
    registration_mode_disabled: "Disabled",
    registration_mode_invite_only: "Invite only",
    registration_mode_automatic: "Automatic",
    linking_label: "Existing account linking",
    linking_confirm: "Verified email plus explicit confirmation",
    linking_auto: "Automatic for trusted verified email",
    linking_disabled: "Disabled",
    privileged_auto_link_label: "Allow automatic linking for privileged memberships",
    method_enabled_label: "Enabled",
    method_sort_order_label: "Order",
    totp_required_label: "Require an authenticator app",
    totp_enforcement_label: "Enforcement",
    totp_enforcement_next_login: "At the next login",
    totp_enforcement_immediate: "Immediately for existing sessions",
    totp_enforcement_grace: "After a grace deadline",
    totp_grace_until_label: "Grace deadline",
    totp_grace_until_hint: "Applies only with grace enforcement. UTC date and time.",
    totp_roles_label: "Required for roles",
    totp_roles_hint: "Leave empty to require two-factor authentication for every site member.",
    role_admin: "Admin",
    role_developer: "Developer",
    role_builder: "Builder",
    role_author: "Author",
    role_publisher: "Publisher",
    role_supporter: "Supporter",
    role_accountant: "Accountant",
    provider_client_id_label: "Client ID",
    provider_tenant_label: "Tenant",
    provider_tenant_placeholder: "common, organizations, consumers, or tenant UUID",
    provider_client_secret_label: "Client secret",
    provider_secret_status_configured: "configured",
    provider_secret_status_missing: "missing",
    provider_secret_hint: "Leave empty to keep the currently stored secret.",
    provider_enabled_label: "Installation enabled",
    provider_login_enabled_label: "Offer on login",
    provider_sort_order_label: "Order",
    provider_save_label: "Save",
    provider_error_title: "Authentication settings error",
    provider_error_load: "Authentication settings could not be loaded.",
    provider_error_save: "Authentication settings could not be saved.",
    provider_success_title: "Authentication settings saved.",
    installations_table_label: "Provider installations",
    installations_empty: "No provider installations yet.",
    installation_key_label: "Installation key",
    installation_key_hint: "Stable lowercase slug, unique per site (for example google-workspace).",
    installation_key_invalid: "Use a lowercase slug of letters, digits, and dashes.",
    installation_provider_label: "Provider",
    installation_tenant_hint: "Microsoft only: common, organizations, consumers, or a tenant UUID.",
    installation_callback_origin_label: "Callback origin",
    installation_callback_origin_hint: "Optional origin from the allowedCallbackOrigins policy. Empty uses the site's public base URL.",
    installation_callback_uri_label: "Callback URI",
    installation_validation_label: "Validation",
    installation_secret_label: "Secret",
    installation_linked_identities_label: "Linked identities",
    installation_action_test: "Test",
    installation_action_edit: "Edit",
    installation_action_delete: "Delete",
    installation_delete_title: "Delete this installation?",
    installation_delete_text: "Linked identities lose this login path. The linked-identities column shows how many site members are affected.",
    installation_delete_irreversible: "Deleting removes the stored secret and cannot be undone.",
    installation_create_title: "Add installation",
    installation_create_description: "Register an identity provider installation. The callback URI to register at the provider appears in the table.",
    installation_edit_title: "Edit installation",
    installation_edit_description: "Pick a row's edit action to load an installation into this form.",
    confirm_ok: "Confirm",
    confirm_cancel: "Cancel",
    submit_label: "Save",
  },
});

export async function getPhiAuthAdminSettingsLabels(options: PhiGlobalTranslatorOptions) {
  const labels = await getPhiLabelSet(options, PHI_AUTH_ADMIN_SETTINGS_LABEL_SET);
  return {
    pageTitle: labels.page_title,
    pageDescription: labels.page_description,
    sections: {
      policy: { title: labels.policy_title, description: labels.policy_description },
      password: { title: labels.password_title, description: labels.password_description },
      totp: { title: labels.totp_title, description: labels.totp_description },
      providers: { title: labels.providers_title, description: labels.providers_description },
    },
    policy: {
      registrationMode: labels.registration_mode_label,
      registrationModeDisabled: labels.registration_mode_disabled,
      registrationModeInviteOnly: labels.registration_mode_invite_only,
      registrationModeAutomatic: labels.registration_mode_automatic,
      linking: labels.linking_label,
      linkingConfirm: labels.linking_confirm,
      linkingAuto: labels.linking_auto,
      linkingDisabled: labels.linking_disabled,
      privilegedAutoLink: labels.privileged_auto_link_label,
    },
    method: {
      enabled: labels.method_enabled_label,
      sortOrder: labels.method_sort_order_label,
    },
    totp: {
      required: labels.totp_required_label,
      enforcement: labels.totp_enforcement_label,
      enforcementNextLogin: labels.totp_enforcement_next_login,
      enforcementImmediate: labels.totp_enforcement_immediate,
      enforcementGrace: labels.totp_enforcement_grace,
      graceUntil: labels.totp_grace_until_label,
      graceUntilHint: labels.totp_grace_until_hint,
      roles: labels.totp_roles_label,
      rolesHint: labels.totp_roles_hint,
    },
    roles: {
      admin: labels.role_admin,
      developer: labels.role_developer,
      builder: labels.role_builder,
      author: labels.role_author,
      publisher: labels.role_publisher,
      supporter: labels.role_supporter,
      accountant: labels.role_accountant,
    },
    installations: {
      tableLabel: labels.installations_table_label,
      empty: labels.installations_empty,
      installationKey: labels.installation_key_label,
      installationKeyHint: labels.installation_key_hint,
      installationKeyInvalid: labels.installation_key_invalid,
      provider: labels.installation_provider_label,
      tenantHint: labels.installation_tenant_hint,
      callbackOrigin: labels.installation_callback_origin_label,
      callbackOriginHint: labels.installation_callback_origin_hint,
      callbackUri: labels.installation_callback_uri_label,
      validation: labels.installation_validation_label,
      secret: labels.installation_secret_label,
      linkedIdentities: labels.installation_linked_identities_label,
      actionTest: labels.installation_action_test,
      actionEdit: labels.installation_action_edit,
      actionDelete: labels.installation_action_delete,
      deleteTitle: labels.installation_delete_title,
      deleteText: labels.installation_delete_text,
      deleteIrreversible: labels.installation_delete_irreversible,
      createTitle: labels.installation_create_title,
      createDescription: labels.installation_create_description,
      editTitle: labels.installation_edit_title,
      editDescription: labels.installation_edit_description,
      confirmOk: labels.confirm_ok,
      confirmCancel: labels.confirm_cancel,
    },
    providers: {
      clientId: labels.provider_client_id_label,
      tenant: labels.provider_tenant_label,
      tenantPlaceholder: labels.provider_tenant_placeholder,
      clientSecret: labels.provider_client_secret_label,
      secretStatusConfigured: labels.provider_secret_status_configured,
      secretStatusMissing: labels.provider_secret_status_missing,
      secretHint: labels.provider_secret_hint,
      enabled: labels.provider_enabled_label,
      loginEnabled: labels.provider_login_enabled_label,
      sortOrder: labels.provider_sort_order_label,
      save: labels.provider_save_label,
      errorTitle: labels.provider_error_title,
      errorLoad: labels.provider_error_load,
      errorSave: labels.provider_error_save,
      successTitle: labels.provider_success_title,
    },
    submitLabel: labels.submit_label,
  };
}

export type PhiAuthAdminSettingsLabels = Awaited<ReturnType<typeof getPhiAuthAdminSettingsLabels>>;
